import type { Preferences } from './types';

export type Language = Preferences['language'];
export type MessageVariables = Record<string, string | number>;

const en = {
  projectName: 'Project name', sourceFolder: 'Source folder', targetFolder: 'Target folder', extensions: 'Extensions',
  filenameCondition: 'Filename condition', keyLength: 'Key length', keyDelimiter: 'Key delimiter', targetSubfolder: 'Target subfolder',
  folderKeyLength: 'Folder key length', folderDelimiter: 'Folder delimiter', compareLength: 'Comparison length',
  browserPreview: 'Browser preview mode. File operations are available in the desktop app.',
  projectAdded: 'A new project was added. Select each item to configure it.', projectNameRequired: 'Enter a project name.',
  desktopFolderOnly: 'Folder selection is available in the desktop app.', folderChanged: '{side} folder updated.',
  source: 'Source', target: 'Target', tagNameRequired: 'Enter a tag name.', tagNameTooLong: 'Tag names must be 80 characters or fewer.',
  duplicateTagName: 'A tag with the same name already exists.', tagSaved: 'Saved the “{name}” tag.',
  tagRenamed: 'Renamed the tag to “{name}”.', tagApplied: 'Applied the “{name}” tag.', tagUpdated: 'Updated the “{name}” tag.',
  deleteTagConfirm: 'Delete the “{name}” tag? Rules already applied to projects will remain unchanged.', tagDeleted: 'Deleted the “{name}” tag.',
  extensionRequired: 'Enter at least one extension.', filterTextRequired: 'Enter text for each filename condition.',
  keyLengthInvalid: 'Key length must be at least 1.', delimiterRequired: 'Enter a delimiter.', compareLengthInvalid: 'Target comparison length must be at least 1.',
  rulesSaved: 'Rules saved.', deleteProjectConfirm: 'Delete the “{name}” project settings? No files will be deleted.',
  allFiles: 'All files', recursive: 'Include subfolders', currentFolder: 'Current folder', extensionsUnset: 'No extensions',
  desktopMoveOnly: 'File preview and moving are available only in the desktop app.', scanning: 'Scanning files…',
  moving: 'Moving files. Do not close the app…', reviewItems: 'Some items need your attention.', moveComplete: 'File move completed.',
  cancelling: 'The run will stop at the next safe point after the current file finishes…', desktopHistoryOnly: 'Run history is available in the desktop app.',
  desktopExportOnly: 'Settings export is available in the desktop app.', exportTitle: 'Export MoveMgr settings', exported: 'Settings exported.',
  desktopImportOnly: 'Settings import is available in the desktop app.', importTitle: 'Import MoveMgr settings',
  importModeConfirm: 'Select OK to append projects to the current list.\nSelect Cancel to replace the current settings.',
  projectsAppended: 'Projects appended.', settingsReplaced: 'Settings replaced.',
  sourceRuleTags: 'Source rule tags', targetRuleTags: 'Target rule tags', sourceTags: 'Source tags', targetTags: 'Target tags',
  saveNewTag: 'Save current rules as a new tag', updateTag: 'Save current rules to selected tag', renameTag: 'Rename selected tag', deleteTag: 'Delete selected tag',
  applyTag: 'Apply “{name}” rules now', applyTagAria: 'Apply tag {name}', noTags: 'No saved tags.', tagName: 'Tag name',
  saveName: 'Save name', cancelName: 'Cancel tag name entry', loading: 'Preparing MoveMgr…', appMenu: 'App menu',
  history: 'Run history', import: 'Import', export: 'Export', settings: 'Settings', manual: 'Manual',
  workspace: 'YOUR WORKSPACE', heroTitle: 'Organize files, your rules.', heroBody: 'Save rules for each project and run the jobs you need at once.',
  addProject: 'Add project', projectTools: 'Project run tools', selectAll: 'Select all', clearAll: 'Clear all',
  selectionCount: 'Selected {selected} / Total {total}', setupNeededCount: ' · Setup needed {count}', previewScope: 'Preview selected scope',
  finishRequired: 'Complete the required settings in the selected scope first.', runScope: 'Run selected scope', preview: 'Preview',
  runSome: 'Run selected ({count})', runAll: 'Run all ({count})', projectList: 'Project list', selectRun: 'Select · Run',
  sourceRules: 'Source rules', targetRules: 'Target rules', management: 'Manage', noProjects: 'No projects yet. Add the first row and configure each column.',
  addFirstRow: 'Add first row', selectProject: 'Select {name}', runOneAria: 'Run {name} only', runThisProject: 'Run only this project',
  setupNeeded: 'Setup needed', projectNameAria: 'Project name', renameProject: 'Rename project', clickToRename: 'Click to rename',
  chooseSourceFolder: 'Choose source folder', chooseTargetFolder: 'Choose target folder', notSet: 'Not set', clickToChoose: 'Click to choose',
  editSourceRules: 'Edit source rules', projectManagement: 'Manage {name}', moveUp: 'Move up', moveDown: 'Move down', duplicateProject: 'Duplicate project',
  duplicate: 'Duplicate', deleteProject: 'Delete project', delete: 'Delete', selectionHint: 'When no projects are selected, all projects run in list order. Run buttons are disabled if required settings are missing in the scope.',
  working: 'Working', settingsSaved: 'Settings saved', saving: 'Saving…', previewOn: 'Preview before run on', quickRunOn: 'Quick run on', rememberChecks: 'Selections remembered', closeError: 'Dismiss error',
  sourceRulesHelp: 'Choose which files to take from the source folder.', close: 'Close', selectedExtensions: 'Selected extensions',
  commaSeparated: 'Extensions — comma separated', includeHidden: 'Include hidden files', filenameConditions: 'Filename conditions',
  conditionsHelp: 'When multiple conditions are added, files must match all of them. Extensions are not checked.', startsWith: 'Starts with', contains: 'Contains',
  endsWith: 'Ends with', equals: 'Exact match', text: 'Text', removeCondition: 'Remove condition', addCondition: 'Add condition', cancel: 'Cancel', saveSourceRules: 'Save source rules',
  targetRulesHelp: 'Build a key from the filename and choose its destination folder.', extractKey: 'Extract key from filename', extractionMethod: 'Extraction method',
  wholeName: 'Whole name', firstNChars: 'First N characters', beforeDelimiter: 'Before delimiter', characterCount: 'Character count', delimiter: 'Delimiter',
  whenMissingDelimiter: 'When delimiter is missing', skip: 'Skip', useWholeName: 'Use whole name', ignoreCase: 'Ignore case', destination: 'Destination',
  destinationMethod: 'Destination method', targetRootDirect: 'Directly in target folder', fixedSubfolder: 'Specified subfolder', matchSubfolder: 'Find an existing folder by key',
  keySubfolder: 'Folder named after the key', subfolder: 'Subfolder', completedPlaceholder: 'completed/2026', createIfMissing: 'Create if missing',
  baseSubfolder: 'Parent subfolder — empty means target root', searchBase: 'Search base subfolder', emptyMeansRoot: 'Empty means target root',
  extractFolderKey: 'Extract comparison value from folder name', wholeFolderName: 'Whole folder name', folderFirstNChars: 'First N folder characters', folderBeforeDelimiter: 'Before folder delimiter',
  folderExtractLength: 'Folder extraction length', comparisonMethod: 'Comparison method', keyEquals: 'Exactly equals the key', folderStartsWithKey: 'Folder starts with the key',
  prefixesEqual: 'First N characters are equal', comparisonLength: 'Comparison length', whenNoMatch: 'When no folder matches', createKeyFolder: 'Create key folder',
  nameConflict: 'Same-name file', renameWithNumber: 'Add a number', saveTargetRules: 'Save target rules', moveResult: 'Move result', reviewBeforeMove: 'Review before moving',
  moved: 'Moved', skipped: 'Skipped', failed: 'Failed', sourceRetained: 'Source retained', project: 'Project', original: 'Source', finalLocation: 'Final location', status: 'Status',
  scheduled: 'To move', blocked: 'Blocked', originalFile: 'Source file', key: 'Key', decision: 'Decision', descending: 'descending', ascending: 'ascending', sort: 'sort',
  move: 'Move', cancelRun: 'Cancel run', movingShort: 'Moving…', startMove: 'Start move ({count})', noHistory: 'No run history yet.',
  historySummary: 'Moved {moved} · Skipped {skipped} · Failed {failed} · Source retained {retained}', preferences: 'PREFERENCES', theme: 'Theme',
  themeSystem: 'System setting', themeLight: 'Light', themeDark: 'Dark', previewBeforeRun: 'Preview before run', previewDescription: 'Show the move plan before the run starts.',
  configLocation: 'Settings location: {path}', language: 'Language', manualTitle: 'MoveMgr Manual',
  newProject: 'New project', copySuffix: ' copy',
  whenMultipleMatches: 'When multiple folders match',
  multipleMatchesSkip: 'Skip', multipleMatchesFirst: 'Send all to the first folder', multipleMatchesRoundRobin: 'Distribute evenly in turn',
  multipleMatchesHelp: 'Folders are ordered by name. Rotation restarts for each project plan and matching folder group; skipped files do not consume a turn.',
  summaryMultipleMatches: 'Multiple matches: {policy}',
  moveUnit: 'Move unit', moveByFile: 'Individual files', moveByNameGroup: 'Files with the same name as a group',
  moveUnitHelp: 'Group files in the same source folder by name without the extension, such as clip.mp4, clip.txt, and clip.png. Files passing the source filters share one destination, and round-robin distribution advances once per group. The target ignore-case setting also applies to grouping.',
  reasonKeyTooShort: 'The name is shorter than the required length.', reasonDelimiterMissing: 'The name does not contain the delimiter.', reasonEmptyKey: 'The key is empty.',
  reasonNoTarget: 'No matching subfolder was found.', reasonAmbiguousTarget: 'More than one subfolder matched.', reasonInvalidTarget: 'The key cannot be used as a folder name.',
  reasonTargetExists: 'A file with the same name already exists.', reasonTargetFolderMissing: 'The destination subfolder does not exist.',
  summaryKey: 'Key: {value}', summaryFilenameWhole: 'whole filename', summaryFilenameFirst: 'first {count} filename characters', summaryFilenameBefore: 'filename before “{delimiter}”',
  summaryFolderWhole: 'whole folder name', summaryFolderFirst: 'first {count} folder characters', summaryFolderBefore: 'folder name before “{delimiter}”',
  summaryRoot: 'Destination: directly in target folder', summaryFixed: 'Destination: {path} subfolder', summaryKeyFolder: 'Destination: key folder under {path}',
  summaryExisting: 'Destination: existing folder under {path}', summaryMissing: '(not set)', summaryTargetRoot: 'target root', summaryCreate: 'create', summarySkip: 'skip',
  summaryFolderMissing: 'If folder is missing: {action} · {conflict}', summaryCompareEquals: 'exact match', summaryCompareStarts: 'folder starts with key',
  summaryComparePrefix: 'first {count} characters match', summaryFolderCompare: '{folderKey} · {comparison}', summaryNoMatch: 'No match: {action} · {conflict}',
  summaryConflictSkip: 'skip same-name file', summaryConflictRename: 'number same-name file'
} as const;

export type MessageKey = keyof typeof en;

const ko: Record<MessageKey, string> = {
  ...en,
  moveUnit: '이동 단위', moveByFile: '파일 단위', moveByNameGroup: '같은 파일명 묶음 단위',
  moveUnitHelp: '같은 소스 폴더의 clip.mp4, clip.txt, clip.png처럼 확장자를 제외한 이름으로 묶습니다. 소스 조건을 통과한 파일은 같은 목적지로 이동하고, 균등 배분 차례는 묶음마다 한 번만 넘어갑니다. 타겟의 대소문자 무시 설정도 적용됩니다.',
  whenMultipleMatches: '일치하는 폴더가 여러 개일 때',
  multipleMatchesSkip: '건너뛰기', multipleMatchesFirst: '첫 번째 폴더에 모으기', multipleMatchesRoundRobin: '순서대로 균등 배분',
  multipleMatchesHelp: '폴더 이름순으로 선택합니다. 순환은 프로젝트의 이동 계획마다 일치 폴더 그룹별로 처음부터 시작하며, 건너뛴 파일은 차례를 소비하지 않습니다.',
  summaryMultipleMatches: '복수 일치: {policy}',
  projectName: '프로젝트명', sourceFolder: '소스 폴더', targetFolder: '타겟 폴더', extensions: '확장자', filenameCondition: '파일명 조건', keyLength: '분류 글자 수', keyDelimiter: '분류 구분자', targetSubfolder: '타겟 하위 폴더', folderKeyLength: '폴더 추출 글자 수', folderDelimiter: '폴더 구분자', compareLength: '비교 글자 수',
  browserPreview: '브라우저 미리보기 모드입니다. 실제 파일 기능은 데스크톱 앱에서 동작합니다.', projectAdded: '새 프로젝트를 추가했습니다. 각 항목을 눌러 설정하세요.', projectNameRequired: '프로젝트 이름을 입력해주세요.', desktopFolderOnly: '폴더 선택은 데스크톱 앱에서 사용할 수 있습니다.', folderChanged: '{side} 폴더를 변경했습니다.', source: '소스', target: '타겟', tagNameRequired: '태그 이름을 입력해주세요.', tagNameTooLong: '태그 이름은 80글자 이하로 입력해주세요.', duplicateTagName: '같은 이름의 태그가 이미 있습니다.', tagSaved: '“{name}” 태그를 저장했습니다.', tagRenamed: '태그 이름을 “{name}”(으)로 변경했습니다.', tagApplied: '“{name}” 태그를 적용했습니다.', tagUpdated: '“{name}” 태그의 내용을 갱신했습니다.', deleteTagConfirm: '“{name}” 태그를 삭제할까요? 프로젝트에 이미 적용된 조건은 그대로 유지됩니다.', tagDeleted: '“{name}” 태그를 삭제했습니다.',
  extensionRequired: '확장자를 하나 이상 입력해주세요.', filterTextRequired: '파일명 조건의 문자열을 입력해주세요.', keyLengthInvalid: '분류 글자 수는 1 이상이어야 합니다.', delimiterRequired: '구분자를 입력해주세요.', compareLengthInvalid: '타겟 비교 글자 수는 1 이상이어야 합니다.', rulesSaved: '조건을 저장했습니다.', deleteProjectConfirm: '“{name}” 프로젝트 설정을 삭제할까요? 파일은 삭제되지 않습니다.', allFiles: '모든 파일', recursive: '하위 폴더 포함', currentFolder: '현재 폴더', extensionsUnset: '확장자 미지정', desktopMoveOnly: '실제 파일 미리보기와 이동은 데스크톱 앱에서만 사용할 수 있습니다.', scanning: '파일을 검사하고 있습니다…', moving: '파일을 이동하고 있습니다. 앱을 종료하지 마세요…', reviewItems: '일부 항목을 확인해야 합니다.', moveComplete: '파일 이동을 완료했습니다.', cancelling: '현재 파일 처리가 끝나는 안전한 지점에서 취소합니다…', desktopHistoryOnly: '실행 기록은 데스크톱 앱에서 확인할 수 있습니다.', desktopExportOnly: '설정 내보내기는 데스크톱 앱에서 사용할 수 있습니다.', exportTitle: 'MoveMgr 설정 내보내기', exported: '설정을 내보냈습니다.', desktopImportOnly: '설정 가져오기는 데스크톱 앱에서 사용할 수 있습니다.', importTitle: 'MoveMgr 설정 가져오기', importModeConfirm: '확인을 누르면 현재 프로젝트 뒤에 추가합니다.\n취소를 누르면 기존 설정을 교체합니다.', projectsAppended: '프로젝트를 추가했습니다.', settingsReplaced: '설정을 교체했습니다.',
  sourceRuleTags: '소스 조건 태그', targetRuleTags: '타겟 조건 태그', sourceTags: '소스 태그', targetTags: '타겟 태그', saveNewTag: '현재 조건을 새 태그로 저장', updateTag: '선택한 태그에 현재 조건 저장', renameTag: '선택한 태그 이름 변경', deleteTag: '선택한 태그 삭제', applyTag: '“{name}” 조건을 즉시 적용', applyTagAria: '태그 {name} 적용', noTags: '저장한 태그가 없습니다.', tagName: '태그 이름', saveName: '이름 저장', cancelName: '태그 이름 입력 취소', loading: 'MoveMgr를 준비하고 있습니다…', appMenu: '앱 메뉴', history: '실행 기록', import: '가져오기', export: '내보내기', settings: '설정', manual: 'Manual', workspace: 'YOUR WORKSPACE', heroTitle: '파일 정리, 규칙대로 간편하게.', heroBody: '프로젝트별 조건을 저장하고 필요한 작업을 한 번에 실행하세요.', addProject: '프로젝트 추가', projectTools: '프로젝트 실행 도구', selectAll: '전체 선택', clearAll: '전체 해제', selectionCount: '선택 {selected} / 전체 {total}', setupNeededCount: ' · 설정 필요 {count}', previewScope: '선택 범위 미리보기', finishRequired: '선택 범위의 필수 설정을 먼저 완료해주세요.', runScope: '선택 범위 실행', preview: '미리보기', runSome: '일부 실행 ({count})', runAll: '전체 실행 ({count})', projectList: '프로젝트 목록', selectRun: '선택·실행', sourceRules: '소스 조건', targetRules: '타겟 조건', management: '관리', noProjects: '등록된 프로젝트가 없습니다. 첫 행을 추가해 각 열에서 바로 설정하세요.', addFirstRow: '첫 행 추가', selectProject: '{name} 선택', runOneAria: '{name} 단일 실행', runThisProject: '이 프로젝트만 실행', setupNeeded: '설정 필요', projectNameAria: '프로젝트 이름', renameProject: '프로젝트명 변경', clickToRename: '눌러서 이름 변경', chooseSourceFolder: '소스 폴더 선택', chooseTargetFolder: '타겟 폴더 선택', notSet: '미설정', clickToChoose: '눌러서 선택', editSourceRules: '소스 조건 변경', projectManagement: '{name} 관리', moveUp: '위로 이동', moveDown: '아래로 이동', duplicateProject: '프로젝트 복제', duplicate: '복제', deleteProject: '프로젝트 삭제', delete: '삭제', selectionHint: '선택한 프로젝트가 없으면 전체 프로젝트를 목록 순서대로 실행합니다. 필수 설정이 비어 있는 프로젝트가 실행 범위에 포함되면 실행 버튼이 비활성화됩니다.', working: '작업 중', settingsSaved: '설정 저장됨', saving: '저장 중…', previewOn: '실행 전 미리보기 켜짐', quickRunOn: '빠른 실행 켜짐', rememberChecks: '체크 상태 유지', closeError: '오류 닫기',
  sourceRulesHelp: '소스 폴더에서 어떤 파일을 가져올지 설정합니다.', close: '닫기', selectedExtensions: '선택한 확장자', commaSeparated: '확장자 — 쉼표로 구분', includeHidden: '숨김 파일 포함', filenameConditions: '파일명 조건', conditionsHelp: '여러 조건을 추가하면 모든 조건을 만족하는 파일만 선택됩니다. 확장자는 제외한 이름을 검사합니다.', startsWith: '시작 문자열', contains: '포함 문자열', endsWith: '끝 문자열', equals: '전체 일치', text: '문자열', removeCondition: '조건 삭제', addCondition: '조건 추가', cancel: '취소', saveSourceRules: '소스 조건 저장', targetRulesHelp: '파일명에서 분류값을 만들고 들어갈 폴더를 결정합니다.', extractKey: '파일명에서 분류값 추출', extractionMethod: '추출 방법', wholeName: '이름 전체', firstNChars: '앞 N글자', beforeDelimiter: '구분자 앞까지', characterCount: '글자 수', delimiter: '구분자', whenMissingDelimiter: '구분자가 없을 때', skip: '건너뛰기', useWholeName: '이름 전체 사용', ignoreCase: '대소문자 무시', destination: '목적지', destinationMethod: '목적지 방식', targetRootDirect: '타겟 폴더에 바로 넣기', fixedSubfolder: '지정한 하위 폴더', matchSubfolder: '분류값으로 기존 폴더 찾기', keySubfolder: '분류값 이름의 폴더', subfolder: '하위 폴더', completedPlaceholder: '완료/2026', createIfMissing: '없으면 만들기', baseSubfolder: '기준 하위 폴더 — 비우면 타겟 루트', searchBase: '검색 기준 하위 폴더', emptyMeansRoot: '비우면 타겟 루트', extractFolderKey: '폴더 이름에서 비교값 추출', wholeFolderName: '폴더 이름 전체', folderFirstNChars: '폴더 앞 N글자', folderBeforeDelimiter: '폴더 구분자 앞까지', folderExtractLength: '폴더 추출 글자 수', comparisonMethod: '비교 방식', keyEquals: '분류값과 정확히 같음', folderStartsWithKey: '폴더가 분류값으로 시작함', prefixesEqual: '양쪽 앞 N글자가 같음', comparisonLength: '비교 글자 수', whenNoMatch: '일치 폴더가 없을 때', createKeyFolder: '분류값 폴더 만들기', nameConflict: '동명 파일', renameWithNumber: '번호 붙이기', saveTargetRules: '타겟 조건 저장', moveResult: '이동 결과', reviewBeforeMove: '이동 전 확인', moved: '이동', skipped: '건너뜀', failed: '실패', sourceRetained: '원본 남음', project: '프로젝트', original: '원본', finalLocation: '최종 위치', status: '상태', scheduled: '이동 예정', blocked: '차단', originalFile: '원본 파일', key: '분류값', decision: '판정', descending: '내림차순', ascending: '오름차순', sort: '정렬', move: '이동', cancelRun: '실행 취소', movingShort: '이동 중…', startMove: '이동 시작 ({count})', noHistory: '아직 실행 기록이 없습니다.', historySummary: '이동 {moved} · 건너뜀 {skipped} · 실패 {failed} · 원본 남음 {retained}', preferences: '환경 설정', theme: '테마', themeSystem: '시스템 설정', themeLight: '밝게', themeDark: '어둡게', previewBeforeRun: '실행 전 미리보기', previewDescription: '실행 버튼을 누르면 이동 계획을 먼저 보여줍니다.', configLocation: '설정 위치: {path}', language: '언어', manualTitle: 'MoveMgr Manual', newProject: '새 프로젝트', copySuffix: ' 복사본',
  reasonKeyTooShort: '이름이 지정한 글자 수보다 짧습니다.', reasonDelimiterMissing: '이름에 구분자가 없습니다.', reasonEmptyKey: '분류값이 비어 있습니다.', reasonNoTarget: '일치하는 하위 폴더가 없습니다.', reasonAmbiguousTarget: '일치하는 하위 폴더가 여러 개입니다.', reasonInvalidTarget: '분류값을 폴더 이름으로 사용할 수 없습니다.', reasonTargetExists: '같은 이름의 파일이 있습니다.', reasonTargetFolderMissing: '목적지 하위 폴더가 없습니다.',
  summaryKey: '분류값: {value}', summaryFilenameWhole: '파일명 전체', summaryFilenameFirst: '파일명 앞 {count}글자', summaryFilenameBefore: '파일명 ‘{delimiter}’ 앞', summaryFolderWhole: '폴더명 전체', summaryFolderFirst: '폴더명 앞 {count}글자', summaryFolderBefore: '폴더명 ‘{delimiter}’ 앞', summaryRoot: '목적지: 타겟 폴더 바로', summaryFixed: '목적지: {path} 하위 폴더', summaryKeyFolder: '목적지: {path} 아래 분류값 폴더', summaryExisting: '목적지: {path}의 기존 폴더', summaryMissing: '(미지정)', summaryTargetRoot: '타겟 루트', summaryCreate: '생성', summarySkip: '건너뜀', summaryFolderMissing: '폴더 없으면 {action} · {conflict}', summaryCompareEquals: '정확 일치', summaryCompareStarts: '폴더명이 분류값으로 시작', summaryComparePrefix: '양쪽 앞 {count}글자 일치', summaryFolderCompare: '{folderKey} · {comparison}', summaryNoMatch: '미일치 {action} · {conflict}', summaryConflictSkip: '동명 파일 건너뜀', summaryConflictRename: '동명 파일 번호 붙임'
};

const ja: Record<MessageKey, string> = {
  ...en,
  moveUnit: '移動単位', moveByFile: 'ファイル単位', moveByNameGroup: '同じ名前のファイルをまとめる',
  moveUnitHelp: '同じソースフォルダーの clip.mp4、clip.txt、clip.png のように、拡張子を除いた名前でまとめます。ソース条件に一致したファイルは同じ保存先へ移動し、均等な振り分けの順番はグループごとに一度だけ進みます。ターゲットの大文字と小文字を無視する設定も適用されます。',
  whenMultipleMatches: '複数のフォルダーが一致する場合',
  multipleMatchesSkip: 'スキップ', multipleMatchesFirst: '最初のフォルダーにまとめる', multipleMatchesRoundRobin: '順番に均等に振り分ける',
  multipleMatchesHelp: 'フォルダー名順に選択します。各プロジェクトの移動計画で、一致するフォルダー群ごとに最初から循環します。スキップしたファイルは順番を進めません。',
  summaryMultipleMatches: '複数一致: {policy}',
  projectName: 'プロジェクト名', sourceFolder: 'ソースフォルダー', targetFolder: 'ターゲットフォルダー', extensions: '拡張子', filenameCondition: 'ファイル名条件', keyLength: '分類文字数', keyDelimiter: '分類区切り文字', targetSubfolder: 'ターゲットのサブフォルダー', folderKeyLength: 'フォルダー抽出文字数', folderDelimiter: 'フォルダー区切り文字', compareLength: '比較文字数',
  browserPreview: 'ブラウザプレビューモードです。実際のファイル操作はデスクトップアプリで利用できます。', projectAdded: '新しいプロジェクトを追加しました。各項目を選択して設定してください。', projectNameRequired: 'プロジェクト名を入力してください。', desktopFolderOnly: 'フォルダー選択はデスクトップアプリで利用できます。', folderChanged: '{side}フォルダーを変更しました。', source: 'ソース', target: 'ターゲット', tagNameRequired: 'タグ名を入力してください。', tagNameTooLong: 'タグ名は80文字以内で入力してください。', duplicateTagName: '同じ名前のタグがすでにあります。', tagSaved: '「{name}」タグを保存しました。', tagRenamed: 'タグ名を「{name}」に変更しました。', tagApplied: '「{name}」タグを適用しました。', tagUpdated: '「{name}」タグを更新しました。', deleteTagConfirm: '「{name}」タグを削除しますか？プロジェクトに適用済みのルールは維持されます。', tagDeleted: '「{name}」タグを削除しました。',
  extensionRequired: '拡張子を1つ以上入力してください。', filterTextRequired: 'ファイル名条件の文字列を入力してください。', keyLengthInvalid: '分類文字数は1以上にしてください。', delimiterRequired: '区切り文字を入力してください。', compareLengthInvalid: '比較文字数は1以上にしてください。', rulesSaved: 'ルールを保存しました。', deleteProjectConfirm: '「{name}」のプロジェクト設定を削除しますか？ファイルは削除されません。', allFiles: 'すべてのファイル', recursive: 'サブフォルダーを含む', currentFolder: '現在のフォルダー', extensionsUnset: '拡張子未指定', desktopMoveOnly: 'ファイルのプレビューと移動はデスクトップアプリでのみ利用できます。', scanning: 'ファイルを確認しています…', moving: 'ファイルを移動しています。アプリを終了しないでください…', reviewItems: '確認が必要な項目があります。', moveComplete: 'ファイルの移動が完了しました。', cancelling: '現在のファイル処理後、安全な時点で停止します…', desktopHistoryOnly: '実行履歴はデスクトップアプリで確認できます。', desktopExportOnly: '設定のエクスポートはデスクトップアプリで利用できます。', exportTitle: 'MoveMgr設定をエクスポート', exported: '設定をエクスポートしました。', desktopImportOnly: '設定のインポートはデスクトップアプリで利用できます。', importTitle: 'MoveMgr設定をインポート', importModeConfirm: 'OKを選ぶと現在のリストに追加します。\nキャンセルを選ぶと既存設定を置き換えます。', projectsAppended: 'プロジェクトを追加しました。', settingsReplaced: '設定を置き換えました。',
  sourceRuleTags: 'ソースルールタグ', targetRuleTags: 'ターゲットルールタグ', sourceTags: 'ソースタグ', targetTags: 'ターゲットタグ', saveNewTag: '現在のルールを新しいタグに保存', updateTag: '選択タグに現在のルールを保存', renameTag: '選択タグの名前を変更', deleteTag: '選択タグを削除', applyTag: '「{name}」のルールを今すぐ適用', applyTagAria: 'タグ{name}を適用', noTags: '保存済みタグはありません。', tagName: 'タグ名', saveName: '名前を保存', cancelName: 'タグ名の入力をキャンセル', loading: 'MoveMgrを準備しています…', appMenu: 'アプリメニュー', history: '実行履歴', import: 'インポート', export: 'エクスポート', settings: '設定', manual: 'Manual', heroTitle: 'ルールどおりに、かんたん整理。', heroBody: 'プロジェクトごとの条件を保存し、必要な処理をまとめて実行できます。', addProject: 'プロジェクト追加', projectTools: 'プロジェクト実行ツール', selectAll: 'すべて選択', clearAll: 'すべて解除', selectionCount: '選択 {selected} / 全体 {total}', setupNeededCount: ' · 要設定 {count}', previewScope: '選択範囲をプレビュー', finishRequired: '選択範囲の必須設定を先に完了してください。', runScope: '選択範囲を実行', preview: 'プレビュー', runSome: '選択を実行 ({count})', runAll: 'すべて実行 ({count})', projectList: 'プロジェクト一覧', selectRun: '選択・実行', sourceRules: 'ソースルール', targetRules: 'ターゲットルール', management: '管理', noProjects: 'プロジェクトがありません。最初の行を追加して各列を設定してください。', addFirstRow: '最初の行を追加', selectProject: '{name}を選択', runOneAria: '{name}のみ実行', runThisProject: 'このプロジェクトのみ実行', setupNeeded: '要設定', projectNameAria: 'プロジェクト名', renameProject: 'プロジェクト名を変更', clickToRename: 'クリックして名前を変更', chooseSourceFolder: 'ソースフォルダーを選択', chooseTargetFolder: 'ターゲットフォルダーを選択', notSet: '未設定', clickToChoose: 'クリックして選択', editSourceRules: 'ソースルールを変更', projectManagement: '{name}を管理', moveUp: '上へ移動', moveDown: '下へ移動', duplicateProject: 'プロジェクトを複製', duplicate: '複製', deleteProject: 'プロジェクトを削除', delete: '削除', selectionHint: '選択がない場合は、すべてのプロジェクトを一覧順に実行します。必須設定が不足していると実行ボタンは無効になります。', working: '処理中', settingsSaved: '設定を保存済み', saving: '保存中…', previewOn: '実行前プレビュー ON', quickRunOn: 'クイック実行 ON', rememberChecks: '選択状態を保持', closeError: 'エラーを閉じる',
  sourceRulesHelp: 'ソースフォルダーから取得するファイルを設定します。', close: '閉じる', selectedExtensions: '選択した拡張子', commaSeparated: '拡張子 — カンマ区切り', includeHidden: '隠しファイルを含む', filenameConditions: 'ファイル名条件', conditionsHelp: '複数条件はすべて一致したファイルを選択します。拡張子を除いた名前を確認します。', startsWith: '先頭文字列', contains: '含む文字列', endsWith: '末尾文字列', equals: '完全一致', text: '文字列', removeCondition: '条件を削除', addCondition: '条件を追加', cancel: 'キャンセル', saveSourceRules: 'ソースルールを保存', targetRulesHelp: 'ファイル名から分類値を作り、保存先を決めます。', extractKey: 'ファイル名から分類値を抽出', extractionMethod: '抽出方法', wholeName: '名前全体', firstNChars: '先頭N文字', beforeDelimiter: '区切り文字の前まで', characterCount: '文字数', delimiter: '区切り文字', whenMissingDelimiter: '区切り文字がない場合', skip: 'スキップ', useWholeName: '名前全体を使用', ignoreCase: '大文字と小文字を無視', destination: '保存先', destinationMethod: '保存先の方式', targetRootDirect: 'ターゲットフォルダーへ直接', fixedSubfolder: '指定したサブフォルダー', matchSubfolder: '分類値で既存フォルダーを検索', keySubfolder: '分類値名のフォルダー', subfolder: 'サブフォルダー', completedPlaceholder: '完了/2026', createIfMissing: 'なければ作成', baseSubfolder: '親サブフォルダー — 空欄はターゲット直下', searchBase: '検索基準サブフォルダー', emptyMeansRoot: '空欄はターゲット直下', extractFolderKey: 'フォルダー名から比較値を抽出', wholeFolderName: 'フォルダー名全体', folderFirstNChars: 'フォルダー名の先頭N文字', folderBeforeDelimiter: 'フォルダー区切り文字の前まで', folderExtractLength: 'フォルダー抽出文字数', comparisonMethod: '比較方法', keyEquals: '分類値と完全一致', folderStartsWithKey: 'フォルダー名が分類値で始まる', prefixesEqual: '両方の先頭N文字が一致', comparisonLength: '比較文字数', whenNoMatch: '一致するフォルダーがない場合', createKeyFolder: '分類値フォルダーを作成', nameConflict: '同名ファイル', renameWithNumber: '番号を付ける', saveTargetRules: 'ターゲットルールを保存', moveResult: '移動結果', reviewBeforeMove: '移動前の確認', moved: '移動', skipped: 'スキップ', failed: '失敗', sourceRetained: '元ファイル残存', project: 'プロジェクト', original: '元ファイル', finalLocation: '最終保存先', status: '状態', scheduled: '移動予定', blocked: 'ブロック', originalFile: '元ファイル', key: '分類値', decision: '判定', descending: '降順', ascending: '昇順', sort: '並べ替え', move: '移動', cancelRun: '実行をキャンセル', movingShort: '移動中…', startMove: '移動開始 ({count})', noHistory: '実行履歴はまだありません。', historySummary: '移動 {moved} · スキップ {skipped} · 失敗 {failed} · 元ファイル残存 {retained}', preferences: '環境設定', theme: 'テーマ', themeSystem: 'システム設定', themeLight: 'ライト', themeDark: 'ダーク', previewBeforeRun: '実行前プレビュー', previewDescription: '実行ボタンを押すと、先に移動計画を表示します。', configLocation: '設定場所: {path}', language: '言語', manualTitle: 'MoveMgr Manual', newProject: '新しいプロジェクト', copySuffix: ' のコピー',
  reasonKeyTooShort: '名前が指定文字数より短いです。', reasonDelimiterMissing: '名前に区切り文字がありません。', reasonEmptyKey: '分類値が空です。', reasonNoTarget: '一致するサブフォルダーがありません。', reasonAmbiguousTarget: '複数のサブフォルダーが一致しました。', reasonInvalidTarget: '分類値をフォルダー名に使用できません。', reasonTargetExists: '同じ名前のファイルがあります。', reasonTargetFolderMissing: '保存先のサブフォルダーがありません。', summaryKey: '分類値: {value}', summaryFilenameWhole: 'ファイル名全体', summaryFilenameFirst: 'ファイル名の先頭{count}文字', summaryFilenameBefore: 'ファイル名の「{delimiter}」より前', summaryFolderWhole: 'フォルダー名全体', summaryFolderFirst: 'フォルダー名の先頭{count}文字', summaryFolderBefore: 'フォルダー名の「{delimiter}」より前', summaryRoot: '保存先: ターゲット直下', summaryFixed: '保存先: {path}サブフォルダー', summaryKeyFolder: '保存先: {path}配下の分類値フォルダー', summaryExisting: '保存先: {path}の既存フォルダー', summaryMissing: '(未設定)', summaryTargetRoot: 'ターゲット直下', summaryCreate: '作成', summarySkip: 'スキップ', summaryFolderMissing: 'フォルダーがない場合: {action} · {conflict}', summaryCompareEquals: '完全一致', summaryCompareStarts: 'フォルダー名が分類値で始まる', summaryComparePrefix: '両方の先頭{count}文字が一致', summaryFolderCompare: '{folderKey} · {comparison}', summaryNoMatch: '不一致: {action} · {conflict}', summaryConflictSkip: '同名ファイルをスキップ', summaryConflictRename: '同名ファイルに番号付与'
};

const zh: Record<MessageKey, string> = {
  ...en,
  moveUnit: '移动单位', moveByFile: '单个文件', moveByNameGroup: '按相同文件名分组',
  moveUnitHelp: '将同一源文件夹中的 clip.mp4、clip.txt、clip.png 等按不含扩展名的名称分组。满足源条件的文件移动到同一位置，轮流分配时每组只占一个轮次。分组也使用目标的忽略大小写设置。',
  whenMultipleMatches: '多个文件夹匹配时',
  multipleMatchesSkip: '跳过', multipleMatchesFirst: '全部放入第一个文件夹', multipleMatchesRoundRobin: '依次均匀分配',
  multipleMatchesHelp: '按文件夹名称排序。每个项目的移动计划按匹配文件夹组从头轮流分配；跳过的文件不会占用轮次。',
  summaryMultipleMatches: '多个匹配：{policy}',
  projectName: '项目名称', sourceFolder: '源文件夹', targetFolder: '目标文件夹', extensions: '扩展名', filenameCondition: '文件名条件', keyLength: '分类字符数', keyDelimiter: '分类分隔符', targetSubfolder: '目标子文件夹', folderKeyLength: '文件夹提取字符数', folderDelimiter: '文件夹分隔符', compareLength: '比较字符数',
  browserPreview: '当前为浏览器预览模式。实际文件操作请使用桌面应用。', projectAdded: '已添加新项目。请选择各项进行设置。', projectNameRequired: '请输入项目名称。', desktopFolderOnly: '文件夹选择仅在桌面应用中可用。', folderChanged: '已更新{side}文件夹。', source: '源', target: '目标', tagNameRequired: '请输入标签名称。', tagNameTooLong: '标签名称不能超过80个字符。', duplicateTagName: '已存在同名标签。', tagSaved: '已保存“{name}”标签。', tagRenamed: '已将标签重命名为“{name}”。', tagApplied: '已应用“{name}”标签。', tagUpdated: '已更新“{name}”标签。', deleteTagConfirm: '要删除“{name}”标签吗？已应用到项目的规则将保留。', tagDeleted: '已删除“{name}”标签。',
  extensionRequired: '请至少输入一个扩展名。', filterTextRequired: '请输入文件名条件文本。', keyLengthInvalid: '分类字符数必须至少为1。', delimiterRequired: '请输入分隔符。', compareLengthInvalid: '目标比较字符数必须至少为1。', rulesSaved: '规则已保存。', deleteProjectConfirm: '要删除“{name}”项目设置吗？不会删除任何文件。', allFiles: '所有文件', recursive: '包含子文件夹', currentFolder: '当前文件夹', extensionsUnset: '未指定扩展名', desktopMoveOnly: '文件预览和移动仅在桌面应用中可用。', scanning: '正在扫描文件…', moving: '正在移动文件。请勿关闭应用…', reviewItems: '部分项目需要检查。', moveComplete: '文件移动完成。', cancelling: '当前文件处理完成后，将在安全位置停止…', desktopHistoryOnly: '运行历史仅在桌面应用中可查看。', desktopExportOnly: '设置导出仅在桌面应用中可用。', exportTitle: '导出 MoveMgr 设置', exported: '设置已导出。', desktopImportOnly: '设置导入仅在桌面应用中可用。', importTitle: '导入 MoveMgr 设置', importModeConfirm: '选择“确定”将项目追加到当前列表。\n选择“取消”将替换现有设置。', projectsAppended: '项目已追加。', settingsReplaced: '设置已替换。',
  sourceRuleTags: '源规则标签', targetRuleTags: '目标规则标签', sourceTags: '源标签', targetTags: '目标标签', saveNewTag: '将当前规则保存为新标签', updateTag: '将当前规则保存到所选标签', renameTag: '重命名所选标签', deleteTag: '删除所选标签', applyTag: '立即应用“{name}”规则', applyTagAria: '应用标签{name}', noTags: '没有已保存的标签。', tagName: '标签名称', saveName: '保存名称', cancelName: '取消输入标签名称', loading: '正在准备 MoveMgr…', appMenu: '应用菜单', history: '运行历史', import: '导入', export: '导出', settings: '设置', manual: 'Manual', heroTitle: '按规则，轻松整理文件。', heroBody: '保存每个项目的条件，一次运行所需任务。', addProject: '添加项目', projectTools: '项目运行工具', selectAll: '全选', clearAll: '取消全选', selectionCount: '已选 {selected} / 总计 {total}', setupNeededCount: ' · 需要设置 {count}', previewScope: '预览所选范围', finishRequired: '请先完成所选范围内的必填设置。', runScope: '运行所选范围', preview: '预览', runSome: '运行所选 ({count})', runAll: '全部运行 ({count})', projectList: '项目列表', selectRun: '选择·运行', sourceRules: '源规则', targetRules: '目标规则', management: '管理', noProjects: '还没有项目。请添加第一行并设置各列。', addFirstRow: '添加第一行', selectProject: '选择{name}', runOneAria: '仅运行{name}', runThisProject: '仅运行此项目', setupNeeded: '需要设置', projectNameAria: '项目名称', renameProject: '重命名项目', clickToRename: '点击重命名', chooseSourceFolder: '选择源文件夹', chooseTargetFolder: '选择目标文件夹', notSet: '未设置', clickToChoose: '点击选择', editSourceRules: '编辑源规则', projectManagement: '管理{name}', moveUp: '上移', moveDown: '下移', duplicateProject: '复制项目', duplicate: '复制', deleteProject: '删除项目', delete: '删除', selectionHint: '未选择项目时，将按列表顺序运行所有项目。如果范围内缺少必填设置，运行按钮将被禁用。', working: '处理中', settingsSaved: '设置已保存', saving: '正在保存…', previewOn: '运行前预览已开启', quickRunOn: '快速运行已开启', rememberChecks: '保留选择状态', closeError: '关闭错误',
  sourceRulesHelp: '设置要从源文件夹获取哪些文件。', close: '关闭', selectedExtensions: '所选扩展名', commaSeparated: '扩展名 — 用逗号分隔', includeHidden: '包含隐藏文件', filenameConditions: '文件名条件', conditionsHelp: '添加多个条件时，文件必须满足全部条件。检查时不含扩展名。', startsWith: '开头为', contains: '包含', endsWith: '结尾为', equals: '完全匹配', text: '文本', removeCondition: '删除条件', addCondition: '添加条件', cancel: '取消', saveSourceRules: '保存源规则', targetRulesHelp: '从文件名生成分类值并决定目标文件夹。', extractKey: '从文件名提取分类值', extractionMethod: '提取方法', wholeName: '完整名称', firstNChars: '前N个字符', beforeDelimiter: '分隔符之前', characterCount: '字符数', delimiter: '分隔符', whenMissingDelimiter: '没有分隔符时', skip: '跳过', useWholeName: '使用完整名称', ignoreCase: '忽略大小写', destination: '目标位置', destinationMethod: '目标方式', targetRootDirect: '直接放入目标文件夹', fixedSubfolder: '指定子文件夹', matchSubfolder: '按分类值查找现有文件夹', keySubfolder: '以分类值命名的文件夹', subfolder: '子文件夹', completedPlaceholder: '完成/2026', createIfMissing: '不存在时创建', baseSubfolder: '父子文件夹 — 留空表示目标根目录', searchBase: '搜索基准子文件夹', emptyMeansRoot: '留空表示目标根目录', extractFolderKey: '从文件夹名称提取比较值', wholeFolderName: '完整文件夹名称', folderFirstNChars: '文件夹名称前N个字符', folderBeforeDelimiter: '文件夹分隔符之前', folderExtractLength: '文件夹提取字符数', comparisonMethod: '比较方式', keyEquals: '与分类值完全相同', folderStartsWithKey: '文件夹以分类值开头', prefixesEqual: '两边前N个字符相同', comparisonLength: '比较字符数', whenNoMatch: '没有匹配文件夹时', createKeyFolder: '创建分类值文件夹', nameConflict: '同名文件', renameWithNumber: '添加编号', saveTargetRules: '保存目标规则', moveResult: '移动结果', reviewBeforeMove: '移动前确认', moved: '已移动', skipped: '已跳过', failed: '失败', sourceRetained: '源文件保留', project: '项目', original: '源文件', finalLocation: '最终位置', status: '状态', scheduled: '计划移动', blocked: '已阻止', originalFile: '源文件', key: '分类值', decision: '判定', descending: '降序', ascending: '升序', sort: '排序', move: '移动', cancelRun: '取消运行', movingShort: '正在移动…', startMove: '开始移动 ({count})', noHistory: '还没有运行历史。', historySummary: '移动 {moved} · 跳过 {skipped} · 失败 {failed} · 保留源文件 {retained}', preferences: '偏好设置', theme: '主题', themeSystem: '跟随系统', themeLight: '浅色', themeDark: '深色', previewBeforeRun: '运行前预览', previewDescription: '点击运行按钮后先显示移动计划。', configLocation: '设置位置：{path}', language: '语言', manualTitle: 'MoveMgr Manual', newProject: '新项目', copySuffix: ' 副本',
  reasonKeyTooShort: '名称短于指定字符数。', reasonDelimiterMissing: '名称中没有分隔符。', reasonEmptyKey: '分类值为空。', reasonNoTarget: '没有匹配的子文件夹。', reasonAmbiguousTarget: '有多个子文件夹匹配。', reasonInvalidTarget: '分类值不能用作文件夹名称。', reasonTargetExists: '存在同名文件。', reasonTargetFolderMissing: '目标子文件夹不存在。', summaryKey: '分类值：{value}', summaryFilenameWhole: '完整文件名', summaryFilenameFirst: '文件名前{count}个字符', summaryFilenameBefore: '文件名“{delimiter}”之前', summaryFolderWhole: '完整文件夹名称', summaryFolderFirst: '文件夹名称前{count}个字符', summaryFolderBefore: '文件夹名称“{delimiter}”之前', summaryRoot: '目标：直接放入目标文件夹', summaryFixed: '目标：{path}子文件夹', summaryKeyFolder: '目标：{path}下的分类值文件夹', summaryExisting: '目标：{path}下的现有文件夹', summaryMissing: '（未设置）', summaryTargetRoot: '目标根目录', summaryCreate: '创建', summarySkip: '跳过', summaryFolderMissing: '文件夹不存在时：{action} · {conflict}', summaryCompareEquals: '完全匹配', summaryCompareStarts: '文件夹以分类值开头', summaryComparePrefix: '前{count}个字符相同', summaryFolderCompare: '{folderKey} · {comparison}', summaryNoMatch: '不匹配：{action} · {conflict}', summaryConflictSkip: '跳过同名文件', summaryConflictRename: '为同名文件添加编号'
};

const messages: Record<Language, Record<MessageKey, string>> = { ko, en, ja, zh };

export function translate(language: Language, key: MessageKey, variables: MessageVariables = {}): string {
  return Object.entries(variables).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    messages[language][key]
  );
}

export const languageOptions: Array<{ value: Language; label: string }> = [
  { value: 'ko', label: '한국어' },
  { value: 'en', label: 'English' },
  { value: 'ja', label: '日本語' },
  { value: 'zh', label: '中文' }
];

export const localeForLanguage: Record<Language, string> = {
  ko: 'ko-KR', en: 'en-US', ja: 'ja-JP', zh: 'zh-CN'
};

export const reasonMessageKeys: Record<string, MessageKey> = {
  KEY_TOO_SHORT: 'reasonKeyTooShort', DELIMITER_MISSING: 'reasonDelimiterMissing', EMPTY_KEY: 'reasonEmptyKey',
  NO_TARGET_MATCH: 'reasonNoTarget', AMBIGUOUS_TARGET: 'reasonAmbiguousTarget', INVALID_TARGET_NAME: 'reasonInvalidTarget',
  TARGET_EXISTS: 'reasonTargetExists', TARGET_FOLDER_MISSING: 'reasonTargetFolderMissing'
};
